<!-- =========================================================================================
  File Name: AddNewDataSidebar.vue
  Description: Add New Data - Sidebar component
  ----------------------------------------------------------------------------------------
  Item Name: Vuesax Admin - VueJS Dashboard Admin Template
  Author: Pixinvent
  Author URL: http://www.themeforest.net/user/pixinvent
========================================================================================== -->


<template>
  <vs-sidebar click-not-close position-right parent="body" default-index="1" color="primary" class="add-new-data-sidebar items-no-padding" spacer v-model="isSidebarActiveLocal">
    <div class="mt-6 flex items-center justify-between px-6">
        <h4>ADD NEW DATA</h4>
        <feather-icon icon="XIcon" @click.stop="isSidebarActiveLocal = false" class="cursor-pointer"></feather-icon>
    </div>
    <vs-divider class="mb-0"></vs-divider>

    <VuePerfectScrollbar class="scroll-area--data-list-add-new pt-4 pb-6" :settings="settings">
    
    <div class="p-6 w-full">
      <template>
        <form-wizard color="rgba(var(--vs-primary), 1)" :title="null" :subtitle="null" finishButtonText="Add Data" @on-complete="submit">
          <tab-content title="Definition" class="mb-5" icon="feather icon-info">

            <!-- tab 1 content -->
            <div class="vx-row">
              <div class="vx-col w-1/2 mt-5">
                <vs-input label="Job No" placeholder="Generated By System" class="w-full" disabled="disabled" />
              </div>
              <div class="vx-col w-1/2 mt-5">
                <vs-input label="Job Open Date" placeholder="20-09-2019" class="w-full" disabled="disabled" />
              </div>
              <div class="vx-col w-1/2 mt-5">
                <vs-input label="Project Name" class="w-full" />
              </div>
              <div class="vx-col w-1/2 mt-5">
                <label for="" class="vs-input--label">Project Date / Period</label>
                <div class="flex justify-between">
                  <datepicker></datepicker>
                  <label for="" class="vs-input--label" style="margin-top: 10px;">Sampai</label>
                  <datepicker></datepicker>    
                </div>
              </div>
              <div class="vx-col w-1/2 mt-5">
                <label for="" class="vs-input--label">Project Description</label>
                <vs-textarea v-model="address" class="mb-5 w-full" />
              </div>
              <div class="vx-col w-1/2 mt-5">
                <vs-select
                autocomplete
                class="w-full" 
                label="Client"
                >
                <vs-select-item :key="index" :value="item.value" :text="item.text" v-for="(item,index) in optionsClient" />
                </vs-select>
              </div>
              <div class="vx-col w-1/2 mt-5">
                <vs-input label="Open By" placeholder="SHE" class="w-full" disabled="disabled" />
              </div>
              <div class="vx-col w-1/2 mt-5">
                <vs-select
                autocomplete
                class="w-full" 
                label="Project Leader"
                >
                <vs-select-item :key="index" :value="item.value" :text="item.text" v-for="(item,index) in optionsProjectLeader" />
                </vs-select>
              </div>
            </div>
          </tab-content>

          <!-- tab 2 content -->
          <tab-content title="Job List Setup" class="mb-5" icon="feather icon-briefcase">
            <template lang="html">
              <div>
                <vs-collapse accordion >
                <vs-collapse-item>
                  <div slot="header" class="flex">
                    <vs-button radius color="danger" type="filled" icon-pack="feather" icon="icon-minus"></vs-button> 
                    <span class="header-accordion-icon">Pitching - Brief</span>
                  </div>
                  <template>
                  <div class="vx-row">
                    <vs-list class="vx-col w-1/2">
                      <vs-list-header title="Job List (master)" color="primary"></vs-list-header>
                      <div class="flex justify-between">
                        <vs-select
                        autocomplete
                        class="mt-5 mr-3 w-full"
                        >
                        <vs-select-item :key="index" :value="item.value" :text="item.text" v-for="(item,index) in optionsActivityType" />
                        </vs-select>
                        <vs-input icon-pack="feather" icon="icon-search" label-placeholder="Search" v-model="search1" class="is-label-placeholder w-full" />
                      </div>
                      
                      <draggable :list="list1" group="people" class="p-2 cursor-move">
                        <vs-list-item v-for="(listItem, index) in list1" :key="index" :title="listItem.name" :subtitle="listItem.type">
                          
                        </vs-list-item>
                      </draggable>

                    </vs-list>

                    <vs-list class="vx-col w-1/2">
                      <vs-list-header title="Job List (assigned)" color="primary"></vs-list-header>
                      <div class="flex justify-between">
                        <vs-select
                        autocomplete
                        class="mt-5 mr-3 w-full"
                        >
                        <vs-select-item :key="index" :value="item.value" :text="item.text" v-for="(item,index) in optionsActivityType" />
                        </vs-select>
                        <vs-input icon-pack="feather" icon="icon-search" label-placeholder="Search" v-model="search1" class="is-label-placeholder w-full" />
                      </div>

                      <draggable :list="list2" group="people" class="p-2 cursor-move">
                        <vs-list-item v-for="(listItem, index) in list2" :key="index" :title="listItem.name" :subtitle="listItem.type">
                          <vs-select
                          autocomplete
                          class="w-full"
                          >
                          <vs-select-item :key="index" :value="item.value" :text="item.text" v-for="(item,index) in optionsGroupExecutor" />
                          </vs-select>
                        </vs-list-item>
                      </draggable>

                    </vs-list>
                  </div>
                </template>
                </vs-collapse-item>
                <vs-collapse-item>
                  <div slot="header" class="flex">
                    <vs-button radius color="danger" type="filled" icon-pack="feather" icon="icon-minus"></vs-button> 
                    <span class="header-accordion-icon">Pitching - Proposal</span>
                  </div>
                  <template>
                    <div class="vx-row">
                      <vs-list class="vx-col w-1/2">
                        <vs-list-header title="Job List (master)" color="primary"></vs-list-header>
                        <div class="flex justify-between">
                          <vs-select
                          autocomplete
                          class="mt-5 mr-3 w-full"
                          >
                          <vs-select-item :key="index" :value="item.value" :text="item.text" v-for="(item,index) in optionsActivityType" />
                          </vs-select>
                          <vs-input icon-pack="feather" icon="icon-search" label-placeholder="Search" v-model="search1" class="is-label-placeholder w-full" />
                        </div>

                        <draggable :list="list1" group="people" class="p-2 cursor-move">
                          <vs-list-item v-for="(listItem, index) in list1" :key="index" :title="listItem.name" :subtitle="listItem.type">
                            
                          </vs-list-item>
                        </draggable>

                      </vs-list>

                      <vs-list class="vx-col w-1/2">
                        <vs-list-header title="Job List (assigned)" color="primary"></vs-list-header>
                        <div class="flex justify-between">
                          <vs-select
                          autocomplete
                          class="mt-5 mr-3 w-full"
                          >
                          <vs-select-item :key="index" :value="item.value" :text="item.text" v-for="(item,index) in optionsActivityType" />
                          </vs-select>
                          <vs-input icon-pack="feather" icon="icon-search" label-placeholder="Search" v-model="search1" class="is-label-placeholder w-full" />
                        </div>

                        <draggable :list="list2" group="people" class="p-2 cursor-move">
                          <vs-list-item v-for="(listItem, index) in list2" :key="index" :title="listItem.name" :subtitle="listItem.type">
                            
                          </vs-list-item>
                        </draggable>

                      </vs-list>
                    </div>
                  </template>
                </vs-collapse-item>
                <vs-collapse-item >
                  <div slot="header" class="flex">
                    <vs-button radius color="danger" type="filled" icon-pack="feather" icon="icon-minus"></vs-button> 
                    <span class="header-accordion-icon">Preparation - Approval</span>
                  </div>
                  <template>
                    <div class="vx-row">
                      <vs-list class="vx-col w-1/2">
                        <vs-list-header title="Job List (master)" color="primary"></vs-list-header>
                          <div class="flex justify-between">
                          <vs-select
                          autocomplete
                          class="mt-5 mr-3 w-full"
                          >
                          <vs-select-item :key="index" :value="item.value" :text="item.text" v-for="(item,index) in optionsActivityType" />
                          </vs-select>
                          <vs-input icon-pack="feather" icon="icon-search" label-placeholder="Search" v-model="search1" class="is-label-placeholder w-full" />
                        </div>

                        <draggable :list="list1" group="people" class="p-2 cursor-move">
                          <vs-list-item v-for="(listItem, index) in list1" :key="index" :title="listItem.name" :subtitle="listItem.type">
                            
                          </vs-list-item>
                        </draggable>

                      </vs-list>

                      <vs-list class="vx-col w-1/2">
                        <vs-list-header title="Job List (assigned)" color="primary"></vs-list-header>
                        <div class="flex justify-between">
                          <vs-select
                          autocomplete
                          class="mt-5 mr-3 w-full"
                          >
                          <vs-select-item :key="index" :value="item.value" :text="item.text" v-for="(item,index) in optionsActivityType" />
                          </vs-select>
                          <vs-input icon-pack="feather" icon="icon-search" label-placeholder="Search" v-model="search1" class="is-label-placeholder w-full" />
                        </div>

                        <draggable :list="list2" group="people" class="p-2 cursor-move">
                          <vs-list-item v-for="(listItem, index) in list2" :key="index" :title="listItem.name" :subtitle="listItem.type">
                            
                          </vs-list-item>
                        </draggable>

                      </vs-list>
                    </div>
                  </template>
                </vs-collapse-item>
                </vs-collapse>
                
                <vs-button radius type="filled" icon-pack="feather" icon="icon-plus" style="margin-left: 25px;"></vs-button>
                <div class="clearfix"></div>
              </div>
            </template>
          </tab-content>

          <tab-content title="Report Access" class="mb-5" icon="feather icon-book">
            <template>
              <div class="vx-row">
                <vs-list class="vx-col w-1/2">
                  <vs-list-header title="User Client Access (master)" color="primary"></vs-list-header>
                    <vs-input icon-pack="feather" icon="icon-search" label-placeholder="Search" v-model="search1" class="is-label-placeholder w-full" />

                  <draggable :list="listClientReport1" group="people" class="p-2 cursor-move">
                    <vs-list-item v-for="(listItem, index) in listClientReport1" :key="index" :title="listItem.name">
                      
                    </vs-list-item>
                  </draggable>

                </vs-list>

                <vs-list class="vx-col w-1/2">
                  <vs-list-header title="User Client Access (granted)" color="primary"></vs-list-header>
                  <vs-input icon-pack="feather" icon="icon-search" label-placeholder="Search" v-model="search1" class="is-label-placeholder w-full" />

                  <draggable :list="listClientReport2" group="people" class="p-2 cursor-move">
                    <vs-list-item v-for="(listItem, index) in listClientReport2" :key="index" :title="listItem.name">
                      
                    </vs-list-item>
                  </draggable>

                </vs-list>
              </div>
            </template>
          </tab-content>

        </form-wizard>
      </template>
    </div>

    </VuePerfectScrollbar>

  </vs-sidebar>
</template>

<script>
import VuePerfectScrollbar from 'vue-perfect-scrollbar'
import Treeselect from '@riophae/vue-treeselect'
import '@riophae/vue-treeselect/dist/vue-treeselect.css'
import {FormWizard, TabContent} from 'vue-form-wizard'
import 'vue-form-wizard/dist/vue-form-wizard.min.css'
import Datepicker from 'vuejs-datepicker'
import draggable from 'vuedraggable'

export default {
  props: {
    isSidebarActive: {
      type: Boolean,
      required: true
    }
  },
  data() {
    return {
      search1:'',
      searchSelect1:'',
      address:'',
      profile:'',
      role:'',
      status:'Active',
      settings: { // perfectscrollbar settings
          maxScrollbarLength: 60,
          wheelSpeed: .60,
      },
      optionsClient:[
        {text:'Bukan Sembarang, PT',value:'Bukan Sembarang, PT'},
        {text:'Maju Bersama Terus, PT',value:'Maju Bersama Terus, PT'}
      ],
      optionsProjectLeader:[
        {text:'WHE',value:'WHE'}
      ],
      optionsGroupExecutor:[
        {text:'Group Executor 1',value:'Group Executor 1'},
        {text:'Group Executor 2',value:'Group Executor 2'},
        {text:'Group Executor 3',value:'Group Executor 3'},
        {text:'Group Executor 4',value:'Group Executor 4'},
        {text:'Group Executor 5',value:'Group Executor 5'},
      ],
      optionsActivityType:[
        {text:'Selling',value:'Selling'},
        {text:'Sampling',value:'Sampling'},
        {text:'Guerilla',value:'Guerilla'},
        {text:'Education',value:'Education'},
        {text:'Exhibition',value:'Exhibition'},
        {text:'Special Exhibition',value:'Special Exhibition'},
        {text:'Thematic Event',value:'Thematic Event'},
        {text:'Gathering',value:'Gathering'},
        {text:'Launching',value:'Launching'},
        {text:'MICE',value:'MICE'}
      ],
      list1: [
        {
          name: "Draft Proposal for Venue",
          type: "Data",
        },
        {
          name: "Venue Option",
          type: "Data",
        },
        {
          name: "Venue Price",
          type: "Data",
        },
        {
          name: "Venue Size (dimensions)",
          type: "Data",
        },
        {
          name: "Venue Layout",
          type: "Photo/Pic",
        }
      ],
      list2: [
        {
          name: "Venue Photo /  Picture",
          type: "Photo/Pic",
        }
      ],
      listClientReport1: [
        {
          name: "User Client 1"
        },
        {
          name: "User Client 2"
        },
        {
          name: "User Client 3"
        }
      ],
      listClientReport2: [
        {
          name: "Super User Client"
        },
      ]
    }
  },
  computed: {
    isSidebarActiveLocal: {
      get() {
        return this.isSidebarActive
      },
      set(val) {
        if(!val) {
          this.$emit('closeSidebar');
          this.initValues();
        }
      }
    }
  },
  methods: {
    initValues() {
      this.address = '';
      this.profile = '';
      this.status = 'Active';
    },
    successUpload(){
      this.$vs.notify({color:'success',title:'Upload Success',text:'Lorem ipsum dolor sit amet, consectetur'})
    },
    submit(){
      this.$parent.dataTable.unshift({'name':this.name,'email':this.email,'role':this.role,'status':this.status});
      this.isSidebarActiveLocal = false;
      this.$vs.notify({
        title:'Success',
        text:'Data Successfully Added',
        color:'success'
      })
    }
  },
  components: {
    VuePerfectScrollbar,
    Treeselect,
    FormWizard,
    TabContent,
    Datepicker,
    draggable
  }
}
</script>

<style lang="scss" scoped>
.add-new-data-sidebar {
  /deep/ .vs-sidebar--background {
    z-index: 52010;
  }

  /deep/ .vs-sidebar {
    z-index: 52010;
    width: 81%;
    max-width: 90vw;

    .img-upload {
      margin-top: 2rem;

      .con-img-upload {
        padding: 0;
      }

      .con-input-upload {
        width: 100%;
        margin: 0;
      }
    }
  }
}

.scroll-area--data-list-add-new {
    height: calc(100% - 4.3rem);
}

.header-accordion-icon{
  margin-top: 7px;
  margin-left: 15px;
}
</style>
